var anynullvalue = null;
console.log("This is a Null Value I am printing here: ", anynullvalue);
var integervalue = 100;
console.log("This is a Integer Value I am printing here: ", integervalue);
var floatingvalue = 3.142;
console.log("This is a Floating Value I am printing here: ", floatingvalue);
var stringvalue = "Abhijeet Singh";
console.log("This is a String Value I am printing here: ", stringvalue);
var undefinedvalue = undefined;
console.log("This is a String Value I am printing here: ", undefinedvalue);
var booleanvalue = true;
console.log("This is a Boolean Value I am printing here: ", booleanvalue);
var anyintegervalue = 100;
console.log("This is a Interger Vlaue I am printing here using any data type: ", anyintegervalue);
var anyfloatingvalue = 3.142;
console.log("This is a Floating Value I am printing here using any data type: ", anyfloatingvalue);
var anystringvalue = "Abhijeet Singh";
console.log("This is a String Value I am printing here using any data type: ", anystringvalue);
var anybooleanvalue = false;
console.log("This is a Boolean Value I am printing here using any data type: ", anybooleanvalue);
var anyundefinedvalue = undefined;
console.log("This is a Undefined Value I am printing here using any data type: ", anyundefinedvalue);
